import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Header & Landing
    features: "Features",
    howItWorks: "How it Works",
    community: "Community",
    reportComplaint: "Register Complaint",
    schemes: "Schemes",
    profile: "Profile",
    dashboard: "Dashboard",
    login: "Login",
    logout: "Logout",
    heroTitleLight: "Empowering",
    heroTitleMiddle: " Gram Panchayats.",
    heroTitleBlue: "Revitalizing",
    heroTitleEnd: " Villages.",
    heroDesc: "A dedicated digital workspace for rural communities to report civic issues like broken streetlights, water supply shortages, and sanitation problems, enabling smooth Gram Panchayat workflows.",
    btnReport: "File Village Complaint",
    activeStatus: "LIVE",
    precisionTitle: "Smarter Governance for",
    precisionField: "Our Villages.",
    precisionDesc: "Our platform maps rural civic grievances using exact GPS coordinate tags and photo uploads, routing tasks directly to Gram Panchayat field workers for transparent and fast resolutions.",
    evidenceLabel: "Verifiable Public Works",
    accuracyLabel: "Panchayat Response Time",
    monitoringLabel: "PANCHAYAT WORKFLOW",
    smartPortal: "Smart Gram Panchayat Portal",
    unifiedEco: "Unified Rural",
    ecosystem: "Ecosystem.",
    reportingTitle: "VILLAGE REPORTING",
    reportingDesc: "Submit localized water leaks, road damages, power cuts, or waste dump issues with live photo proof.",
    adminTitle: "PANCHAYAT ORCHESTRATION",
    adminDesc: "Panchayat admins and Sarpanch approve complaints, allocate budgets, and dispatch workers.",
    volunteerTitle: "FIELD-WORK RESOLUTION",
    volunteerDesc: "Field personnel receive tasks, resolve infrastructure issues, and upload validation reports.",

    // Sidebar
    home: "Home",
    systemOverview: "System Overview",
    fieldWorkers: "Field Workers",
    complaintsMgmt: "Complaints Management",
    settings: "Settings",
    sysAdmin: "System Admin",
    citizen: "Citizen",

    // Login & Signup
    loginTitle: "Citizen & Civic Administration Portal",
    signupTitle: "Register a new citizen or admin account",
    registerHere: "Register Here",
    newToGram: "New to GramSuvidha?",
    loginBtn: "Sign In",
    registerBtn: "Register Now",
    email: "Email Address",
    password: "Password",
    rememberMe: "Remember me",
    forgotPass: "Forgot password?",
    alreadyReg: "Already registered?",
    loginHere: "Login Here",
    regType: "Registration Type",
    pAdmin: "Panchayat Admin",
    firstName: "First Name",
    lastName: "Last Name",
    age: "Age",
    phone: "Mobile Number",
    gender: "Gender",
    selectGender: "Select Gender",
    confirmPass: "Confirm Password",
    villageId: "Official Panchayat / Village ID",
    categoriesTitle: "Select Category to Report",
    categoriesDesc: "Issues will be routed to corresponding Gram Panchayat department",
    waterTitle: "Water & Sanitation",
    waterDesc: "Pipeline leakage, drainage blocks, public toilets",
    lightTitle: "Electricity & Lights",
    lightDesc: "Streetlights not working, loose power lines",
    roadTitle: "Roads & Cleanliness",
    roadDesc: "Potholes, garbage disposal, road obstruction",
    schemeTitle: "Welfare Schemes",
    schemeDesc: "Apply for housing, agricultural, and drinking water schemes"
  },
  hi: {
    // Header & Landing
    features: "विशेषताएं",
    howItWorks: "यह कैसे काम करता है",
    community: "समुदाय",
    reportComplaint: "शिकायत दर्ज करें",
    schemes: "सरकारी योजनाएं",
    profile: "प्रोफाइल विवरण",
    dashboard: "डैशबोर्ड",
    login: "लॉगिन करें",
    logout: "लॉगआउट",
    heroTitleLight: "सशक्त",
    heroTitleMiddle: " ग्राम पंचायत।",
    heroTitleBlue: "सम्पन्न",
    heroTitleEnd: " ग्रामीण भारत।",
    heroDesc: "ग्रामीण नागरिकों के लिए एक समर्पित मंच जहाँ पेयजल आपूर्ति, बंद स्ट्रीटलाइट, क्षतिग्रस्त सड़कें और स्वच्छता जैसी समस्याओं को दर्ज कर पंचायत द्वारा त्वरित समाधान पाया जा सकता है।",
    btnReport: "पंचायत शिकायत दर्ज करें",
    activeStatus: "सक्रिय",
    precisionTitle: "हमारे गाँवों के लिए",
    precisionField: "सशक्त सुशासन।",
    precisionDesc: "हमारा पोर्टल ग्राम पंचायत स्तर की शिकायतों को सटीक जीपीएस लोकेशन और फोटो साक्ष्य के साथ रिकॉर्ड करता है, जिससे पंचायत कर्मी बिना देरी किए सीधे स्थल पर काम शुरू कर सकें।",
    evidenceLabel: "सत्यापित सार्वजनिक कार्य",
    accuracyLabel: "पंचायत प्रतिक्रिया समय",
    monitoringLabel: "सक्रिय पंचायत निगरानी",
    smartPortal: "स्मार्ट ग्राम पंचायत पोर्टल",
    unifiedEco: "एकीकृत ग्रामीण",
    ecosystem: "कार्यप्रणाली।",
    reportingTitle: "ग्रामीण शिकायत रिपोर्टिंग",
    reportingDesc: "टूटी पाइपलाइन, जर्जर सड़कों, बिजली कटौती या कचरे के ढेरों की फोटो के साथ सीधे रिपोर्ट करें।",
    adminTitle: "पंचायत प्रशासनिक प्रबंधन",
    adminDesc: "सरपंच और पंचायत सचिव शिकायतों का सत्यापन कर बजट आवंटन और काम का वितरण करते हैं।",
    volunteerTitle: "क्षेत्रीय सुधार कार्य",
    volunteerDesc: "अधिकृत पंचायत फील्ड कर्मी आवंटित कार्य को पूरा कर स्थल सुधार का डिजिटल प्रमाण जमा करते हैं।",

    // Sidebar
    home: "मुख्य पृष्ठ",
    systemOverview: "सिस्टम सारांश",
    fieldWorkers: "क्षेत्र कार्यकर्ता",
    complaintsMgmt: "शिकायत प्रबंधन",
    settings: "सेटिंग्स",
    sysAdmin: "पंचायत व्यवस्थापक",
    citizen: "नागरिक",

    // Login & Signup
    loginTitle: "नागरिक एवं ग्राम पंचायत प्रशासन पोर्टल",
    signupTitle: "नागरिक या पंचायत अधिकारी का नया खाता बनाएं",
    registerHere: "यहाँ पंजीकरण करें",
    newToGram: "ग्रामसुविधा में नए हैं?",
    loginBtn: "साइन इन करें",
    registerBtn: "पंजीकरण करें",
    email: "ईमेल पता",
    password: "पासवर्ड",
    rememberMe: "मुझे याद रखें",
    forgotPass: "पासवर्ड भूल गए?",
    alreadyReg: "पहले से पंजीकृत हैं?",
    loginHere: "यहाँ लॉगिन करें",
    regType: "पंजीकरण का प्रकार",
    pAdmin: "पंचायत अधिकारी",
    firstName: "पहला नाम",
    lastName: "उपनाम",
    age: "आयु",
    phone: "मोबाइल नंबर",
    gender: "लिंग",
    selectGender: "लिंग चुनें",
    confirmPass: "पासवर्ड की पुष्टि करें",
    villageId: "आधिकारिक पंचायत / ग्राम कोड",
    categoriesTitle: "रिपोर्ट करने के लिए श्रेणी चुनें",
    categoriesDesc: "शिकायतें संबंधित ग्राम पंचायत विभाग को भेजी जाएंगी",
    waterTitle: "पेयजल और स्वच्छता",
    waterDesc: "पाइपलाइन रिसाव, जल निकासी बंद होना, सार्वजनिक शौचालय",
    lightTitle: "बिजली और स्ट्रीटलाइट",
    lightDesc: "स्ट्रीटलाइट खराब होना, ढीले बिजली के तार",
    roadTitle: "सड़कें और साफ-सफाई",
    roadDesc: "गड्ढे, कचरा निपटान, सड़क अवरोध",
    schemeTitle: "कल्याणकारी योजनाएं",
    schemeDesc: "आवास, कृषि और पेयजल योजनाओं के लिए आवेदन करें"
  }
  ,
  extra: {
    en: {
      popularSchemesTitle: 'Popular Welfare Schemes',
      popularSchemesDesc: 'Key schemes with brief descriptions — click to learn more and apply.',
      learnMore: 'Learn more →',
      schemeDetailsLabel: 'Scheme Details',
      eligibilityLabel: 'Eligibility',
      openSchemesPage: 'Open Schemes Page',
      close: 'Close',
      schemesCheckerTitle: 'Schemes Eligibility Checker',
      schemesCheckerDesc: 'Enter your demographic details below. The GramSuvidha engine will recommend government schemes tailored for you.',
      checkEligibilityBtn: 'Check Eligibility',
      noMatchingSchemesMsg: 'No matching schemes found for the entered criteria.',
      tryAdjustMsg: 'Try adjusting the income or age parameters.',
      
      // Dashboards Common & Citizen Dashboard
      citizenDashboard: "Citizen Dashboard",
      welcomeBack: "Welcome back",
      trackIssues: "Track your reported issues and schemes.",
      newComplaint: "New Complaint",
      total: "Total",
      underReview: "Under Review",
      inProgress: "In Progress",
      resolved: "Resolved",
      myComplaints: "My Complaints",
      mySchemes: "My Scheme Applications",
      activeTracking: "ACTIVE TRACKING",
      noComplaints: "No complaints filed yet",
      clickNewComplaint: "Click 'New Complaint' to report an issue in your village.",
      fileFirstComplaint: "File Your First Complaint",
      incident: "Incident",
      currentStatus: "Current Status",
      incidentLocation: "Incident Location",
      progressStage: "Progress Stage",
      registered: "Registered",
      applySchemeBtn: "Apply for Scheme",
      noSchemes: "No scheme applications yet",
      exploreSchemes: "Explore Schemes",
      schemeName: "Scheme Name",
      applicant: "Applicant",
      appliedOn: "Applied On",
      applicationId: "Application ID",
      complaintAnalytics: "Complaint Analytics",
      resolutionStatus: "Resolution Status",
      issuesByCategory: "Issues By Category",
      villageUpdates: "Village Updates & Events",
      latestAnnouncements: "Latest announcements from your Panchayat",
      adminVoting: "Panchayat Administrator Voting",
      voteBestAdmin: "Vote for the best-performing administrator once a year",
      activeElection: "ACTIVE ELECTION",
      electionInactive: "ELECTION INACTIVE",
      electionSchedule: "Election Schedule",
      votingPeriod: "Voting Period",
      noElectionScheduled: "No election scheduled yet.",
      candidateAdmins: "Candidate Administrators",
      electionStandings: "Election Results & Standings",
      noAdminsRegistered: "No administrators registered in your village.",
      myVote: "MY VOTE",
      votes: "votes",
      percentTotal: "of total",
      voteBtn: "Vote",
      loadingStandings: "Loading standings...",
      
      // Admin Dashboard
      infrastructureMetrics: "GramSuvidha infrastructure and performance metrics.",
      adminDetails: "Administrator Details",
      assignedRegion: "Logged-in admin information and assigned region.",
      changePhoto: "Change Photo",
      editDetails: "Edit Details",
      saveChanges: "Save changes",
      cancel: "Cancel",
      village: "Village",
      taluk: "Taluk",
      district: "District",
      state: "State",
      pincode: "Pincode",
      registrationVolume: "Registration Volume",
      liveStatus: "Live Status",
      departmentVelocity: "Department Velocity",
      performanceMatrix: "Performance Matrix",
      citizensUnderAdmin: "Citizens Under Administration",
      publishedVillageUpdates: "Published Village Updates",
      publishAnnouncement: "Publish Announcement",
      addAnnouncement: "Publish New Announcement",
      editAnnouncement: "Edit Announcement",
      title: "Title",
      category: "Category",
      description: "Description / Details",
      eventDate: "Event Date (Optional)",
      scheduleYearlyElection: "Schedule Yearly Election",
      votingStartDate: "Voting Start Date",
      votingEndDate: "Voting End Date",
      saveElectionDates: "Save Election Dates",
      liveElectionStandings: "Live Election Standings",
      totalVotesCast: "Total Votes Cast",
      electionYear: "Election Year",
      rank: "Rank",
      overviewTab: "Overview & Analytics",
      updatesTab: "Village Updates Feed",
      electionTab: "Election Scheduler & Standings",

      // How it Works & Community (Landing Page)
      howItWorksTitle: "How it Works",
      howItWorksDesc: "Simplifying rural civic operations in four easy steps",
      step1Title: "Register with Panchayat ID",
      step1Desc: "Citizens and admins register using a unique official Village ID. This automatically places them in the same localized digital ecosystem.",
      step2Title: "Report Issues & Check Bulletins",
      step2Desc: "Report water, electricity, or waste issues with exact location details, verify scheme eligibility, and view live village announcements.",
      step3Title: "Orchestration & Dispatch",
      step3Desc: "Sarpanch and admins verify complaints, allocate budgets, dispatch field workers, and schedule annual voting calendars.",
      step4Title: "Resolution & Voting",
      step4Desc: "Workers resolve issues and upload proof. Citizens track statuses transparently and cast their vote during the yearly election.",
      
      communityTitle: "Community & Citizen Engagement",
      communityDesc: "Building transparent relationship pathways between citizens, volunteers, and rural leaders",
      comm1Title: "Yearly Administrator Ranking",
      comm1Desc: "One village can register multiple administrators. Citizens can cast their vote once a year to rank the best-performing leaders based on their operational speed, resolution rates, and responsiveness.",
      comm2Title: "SLA Compliance & Action Tracking",
      comm2Desc: "Our system keeps a verified ledger of all civic actions, average resolution times, and department velocities. Citizens can view live status indicators, preventing communication delays or lost complaints.",
      comm1Badge: "Democratic Accountability",
      comm2Badge: "Transparent Resolutions",
      comm1Footer: "Empowers rural citizens to have a direct voice in local governance performance.",
      comm2Footer: "Fosters trust through verifiable proof, logs, and accountability dashboards.",

      // SignUp page
      adminVerifRequired: "Required for administrative verification.",
      villageName: "Village Name",
      male: "Male",
      female: "Female",
      other: "Other",
      registering: "Registering...",
      villageIdCitizenNote: "You must enter the same Village ID your Panchayat Admin used during registration. This links you to the correct admin.",

      // Register Complaint page
      registerNewComplaint: "Register New Complaint",
      complaintHelperText: "Provide detailed information to help our volunteers address the issue.",
      complaintDetailsSection: "1. Complaint Details",
      issueCategory: "Issue Category",
      waterLeakage: "Water Leakage",
      roadDamage: "Road Damage",
      garbageDump: "Garbage Dump",
      electricityIssue: "Electricity Issue",
      drainageIssue: "Drainage Issue",
      priority: "Priority",
      high: "High",
      medium: "Medium",
      low: "Low",
      detailedDescription: "Detailed Description",
      visualEvidence: "2. Visual Evidence & Documentation",
      uploadPrompt: "Click to upload photos, videos or documents",
      uploadFormats: "Images (JPG, PNG), Videos (MP4), Documents (PDF, DOC)",
      uploadLimit: "Up to 5 files (Max 10MB each)",
      browseFiles: "Browse Files",
      locationSection: "3. Location Information",
      currentGPS: "Current GPS",
      manualEntry: "Manual Entry",
      autoDetect: "Auto-Detect My Location",
      finalAddress: "Final Verified Address",
      detectedLocation: "DETECTED LOCATION",
      registeringComplaint: "Registering...",
      ipLogNote: "Your IP address and location will be logged for verification.",

      // Citizen Profile page
      citizenProfile: "Citizen Profile",
      editProfile: "Edit Profile",
      handlingAdmin: "Handling Administrator",
      noAdminFound: "No administrator found",
      ensureVillageId: "Ensure your Village ID is correct.",
      basicDetails: "Basic Details",
      fullName: "Full Name",
      save: "Save",
      myAppliedSchemes: "My Applied Schemes",
      trackApproval: "Track the approval and eligibility of your submitted scheme applications.",
      noSchemesText: "Visit the Schemes section to check your eligibility for government welfare programs and register online.",
      viewDocument: "View Document",
      benefitStart: "Benefit Start:",
      benefitExpiry: "Benefit Expiry:",

      // Admin - Complaints Management
      workersActive: "Workers Active",
      complaintsDesc: "Detailed review and resolution of civic reports.",
      allSubmissions: "All Submissions",
      searchComplaints: "Search by ID or details...",
      allStatuses: "All Statuses",
      awaitingReview: "Awaiting Review",
      complaintDetailsModal: "Complaint Details",
      statusLabel: "Status",
      assignedForce: "Assigned Force",
      actionsLabel: "Actions",
      viewLabel: "View",
      citizenDetails: "Citizen Details",
      locationLabel: "Location",
      updateStatus: "Update Status",
      assignWorker: "Assign Worker",
      noneOption: "None",
      noComplaintsFound: "No complaints found matching current search and filters.",
      loadingComplaints: "Loading complaints...",

      // Admin - Field Workers
      fieldWorkersDesc: "Manage and track the active GramSuvidha workforce.",
      forceOverview: "Force Overview",
      searchWorkers: "Search workers...",
      workerIdentity: "Worker Identity",
      areaVillage: "Area / Village",
      contactLabel: "Contact",
      demographics: "Demographics",
      activeWorker: "Active",
      onLeave: "On Leave",
      resigned: "Resigned",
      addNewWorker: "Add New Worker",
      addWorkerDesc: "Register a new field worker for the GramSuvidha force.",
      phoneNumber: "Phone Number",
      workerVillageNote: "Worker will be automatically assigned to your village.",
      clear: "Clear",
      registerWorker: "Register Worker",
      noWorkersFound: "No field workers found matching search.",
      loadingWorkers: "Loading workers...",
      workerSuccess: "Worker registered successfully!",

      // Admin - Scheme Applicants
      schemeApplicants: "Scheme Applicants",
      totalSubmissionsLabel: "Total Submissions",
      schemeApplicantsDesc: "Review, approve, and manage citizen welfare scheme applications.",
      searchApplicants: "Search by name, scheme, ID...",
      pendingStatus: "Pending",
      approvedStatus: "Approved",
      rejectedStatus: "Rejected",
      tooLateStatus: "Too Late",
      applicantRelAge: "Applicant (Relation, Age)",
      idNumberCol: "ID Number",
      idProofCol: "ID Proof",
      reviewLabel: "Review",
      reviewApplication: "Review Application",
      editStatusParams: "Edit status and validity parameters.",
      schemeLabel: "Scheme",
      relationLabel: "Relation",
      updateAppStatus: "Update Application Status",
      benefitStartDate: "Benefit Start Date",
      benefitExpiryDate: "Benefit Expiry Date",
      uploadedDocument: "Uploaded Document:",
      viewIdProof: "View ID Proof File ↗",
      noAppFound: "No applications found matching search criteria.",
      loadingApps: "Loading scheme applications...",

      // Citizen - Schemes page
      ageYears: "Age (Years)",
      annualIncome: "Annual Income (₹)",
      socialCategory: "Social Category",
      selectCategory: "Select Category",
      primaryOccupation: "Primary Occupation",
      selectOccupation: "Select Occupation",
      recommendedSchemes: "Recommended Schemes",
      highlyEligible: "Highly Eligible",
      youAreEligible: "You are Eligible",
      applicationForm: "Application Form",
      applyingFor: "Applying For",
      applicantNameLabel: "Applicant Name",
      preFilled: "Pre-filled from eligibility criteria",
      idNumberLabel: "ID Number (Aadhaar / PAN)",
      uploadIdProof: "Upload ID Proof (Scan/Photo)",
      submitting: "Submitting...",
      submitApplication: "Submit Application",
      applicationSubmitted: "Application Submitted!",
      schemeSubmittedDesc: "Your application has been successfully submitted and is under review.",
      alreadyRegisteredNotice: "Notice: You have already registered for this scheme under the relationship",
      nodesOperational: "Nodes Operational",
      days7: "7 Days",
      days30: "30 Days",
      notifications: "Notifications",
      noNotifications: "No recent notifications",
      totalRequests: "Total Requests",
      pendingAction: "Pending Action",
      successfulResolutions: "Successful Resolutions",
      activeVolunteers: "Active Volunteers",
      dailyVolumeDesc: "Daily community participation trend.",
      liveStatusDesc: "Operational lifecycle phase.",
      complaintPriorities: "Complaint Priorities",
      deptVelocityDesc: "Performance metrics by category.",
      perfMatrixDesc: "Key operational performance indicators.",
      avgResolutionTime: "Avg Resolution Time",
      slaCompliance: "SLA Compliance (72h)",
      avgAssignments: "Avg Assignments per Worker",
      openTickets: "Open Tickets",
      citizensUnderAdminDesc: "List of all citizens registered in your village/ward.",
      totalCaps: "TOTAL",
      loadingCitizens: "Loading citizens...",
      noCitizensFound: "No citizens found",
      citizensRegisteringNote: "Citizens registering with your Village ID will appear here.",
      yrs: "Yrs",
      notSpecified: "Not specified",
      editAnnouncementDesc: "Update details of this village announcement",
      publishAnnouncementDesc: "Publish election schedules, water disputes, power updates, etc.",
      updateAnnouncement: "Update Announcement",
      publishedUpdatesDesc: "List of announcements visible to your citizens.",
      noAnnouncements: "No announcements published yet.",
      eventDateLabel: "Event Date",
      editLabel: "Edit",
      deleteLabel: "Delete",
      scheduleYearlyElectionDesc: "Define the active voting period for village administrators.",
      activeConfiguration: "Active Configuration:",
      yearLabel: "Year",
      startLabel: "Start",
      endLabel: "End",
      electionsCurrentlyActive: "Elections currently active",
      electionsCurrentlyInactive: "Elections currently inactive",
      liveElectionStandingsDesc: "Performance rating leaderboard based on citizen votes.",
      systemOperationalLogs: "System Operational Logs",
      systemLogsDesc: "Real-time status updates and admin action tracking.",
      closeLogs: "Close Logs",
      updateSuccess: "Announcement updated successfully!",
      publishSuccess: "Announcement published successfully!",
      deleteConfirm: "Are you sure you want to delete this update?",
      deleteSuccess: "Failed to delete update",
      networkError: "Network error",
      scheduling: "Scheduling...",
      electionSaved: "Election scheduled successfully!",
      electionSaveFailed: "Failed to schedule election"
    },
    hi: {
      popularSchemesTitle: 'लोकप्रिय कल्याणकारी योजनाएं',
      popularSchemesDesc: 'संक्षिप्त विवरण के साथ प्रमुख योजनाएँ — अधिक जानने और आवेदन करने के लिए क्लिक करें।',
      learnMore: 'और पढ़ें →',
      schemeDetailsLabel: 'योजना विवरण',
      eligibilityLabel: 'पात्रता',
      openSchemesPage: 'योजनाएँ खोलें',
      close: 'बंद करें',
      schemesCheckerTitle: 'योजना पात्रता चेकर',
      schemesCheckerDesc: 'अपनी जनसांख्यिकीय जानकारी नीचे दर्ज करें। GramSuvidha इंजन आपके लिए उपयुक्त सरकारी योजनाएँ सुझाएगा।',
      checkEligibilityBtn: 'पात्रता जाँचें',
      noMatchingSchemesMsg: 'दिए गए मानदंडों के लिए कोई मिलती-जुलती योजना नहीं मिली।',
      tryAdjustMsg: 'कृपया आय या आयु पैरामीटर समायोजित करके पुनः प्रयास करें।',
      
      // Dashboards Common & Citizen Dashboard
      citizenDashboard: "नागरिक डैशबोर्ड",
      welcomeBack: "आपका स्वागत है",
      trackIssues: "अपनी शिकायतों और योजनाओं की स्थिति ट्रैक करें।",
      newComplaint: "नई शिकायत",
      total: "कुल",
      underReview: "समीक्षाधीन",
      inProgress: "प्रगति पर",
      resolved: "समाधान हुआ",
      myComplaints: "मेरी शिकायतें",
      mySchemes: "मेरे योजना आवेदन",
      activeTracking: "सक्रिय ट्रैकिंग",
      noComplaints: "कोई शिकायत दर्ज नहीं की गई है",
      clickNewComplaint: "अपने गाँव में शिकायत दर्ज करने के लिए 'नई शिकायत' पर क्लिक करें।",
      fileFirstComplaint: "अपनी पहली शिकायत दर्ज करें",
      incident: "घटना",
      currentStatus: "वर्तमान स्थिति",
      incidentLocation: "घटना स्थल",
      progressStage: "प्रगति चरण",
      registered: "पंजीकृत तिथि",
      applySchemeBtn: "योजना के लिए आवेदन करें",
      noSchemes: "कोई योजना आवेदन नहीं है",
      exploreSchemes: "योजनाएं देखें",
      schemeName: "योजना का नाम",
      applicant: "आवेदक",
      appliedOn: "आवेदन तिथि",
      applicationId: "आवेदन आईडी",
      complaintAnalytics: "शिकायत विश्लेषण",
      resolutionStatus: "समाधान की स्थिति",
      issuesByCategory: "श्रेणीवार शिकायतें",
      villageUpdates: "गाँव के समाचार और घोषणाएं",
      latestAnnouncements: "आपकी पंचायत से नवीनतम घोषणाएं",
      adminVoting: "पंचायत अधिकारी मतदान",
      voteBestAdmin: "साल में एक बार सर्वश्रेष्ठ कार्य करने वाले अधिकारी को वोट दें",
      activeElection: "सक्रिय चुनाव",
      electionInactive: "चुनाव निष्क्रिय",
      electionSchedule: "चुनाव अनुसूची",
      votingPeriod: "मतदान की अवधि",
      noElectionScheduled: "इस वर्ष के लिए कोई चुनाव निर्धारित नहीं है।",
      candidateAdmins: "उम्मीदवार अधिकारी",
      electionStandings: "चुनाव परिणाम और स्थिति",
      noAdminsRegistered: "आपके गाँव में कोई अधिकारी पंजीकृत नहीं हैं।",
      myVote: "मेरा वोट",
      votes: "वोट",
      percentTotal: "कुल का",
      voteBtn: "वोट दें",
      loadingStandings: "परिणाम लोड हो रहे हैं...",
      
      // Admin Dashboard
      infrastructureMetrics: "ग्रामसुविधा अवसंरचना और प्रदर्शन संकेतक।",
      adminDetails: "प्रशासक विवरण",
      assignedRegion: "लॉगिन अधिकारी की जानकारी और आवंटित क्षेत्र।",
      changePhoto: "फोटो बदलें",
      editDetails: "विवरण संपादित करें",
      saveChanges: "बदलाव सहेजें",
      cancel: "रद्द करें",
      village: "गाँव",
      taluk: "तालुका",
      district: "जिला",
      state: "राज्य",
      pincode: "पिनकोड",
      registrationVolume: "पंजीकरण वॉल्यूम",
      liveStatus: "लाइव स्थिति",
      departmentVelocity: "विभाग की कार्य गति",
      performanceMatrix: "प्रदर्शन मैट्रिक्स",
      citizensUnderAdmin: "प्रशासन के अंतर्गत नागरिक",
      publishedVillageUpdates: "प्रकाशित गाँव की घोषणाएं",
      publishAnnouncement: "घोषणा प्रकाशित करें",
      addAnnouncement: "नई घोषणा प्रकाशित करें",
      editAnnouncement: "घोषणा संपादित करें",
      title: "शीर्षक",
      category: "श्रेणी",
      description: "विवरण / जानकारी",
      eventDate: "घटना की तिथि (वैकल्पिक)",
      scheduleYearlyElection: "वार्षिक चुनाव निर्धारित करें",
      votingStartDate: "मतदान शुरू होने की तिथि",
      votingEndDate: "मतदान समाप्त होने की तिथि",
      saveElectionDates: "चुनाव तिथियां सहेजें",
      liveElectionStandings: "लाइव चुनाव परिणाम",
      totalVotesCast: "कुल डाले गए वोट",
      electionYear: "चुनाव वर्ष",
      rank: "रैंक",
      overviewTab: "सारांश और विश्लेषण",
      updatesTab: "गाँव के समाचार",
      electionTab: "चुनाव अनुसूची और परिणाम",

      // How it Works & Community (Landing Page)
      howItWorksTitle: "यह कैसे काम करता है",
      howItWorksDesc: "ग्रामीण नागरिक सुविधाओं को चार आसान चरणों में सरल बनाना",
      step1Title: "ग्राम पंचायत कोड से पंजीकरण",
      step1Desc: "नागरिक और अधिकारी एक विशिष्ट ग्राम पंचायत कोड का उपयोग करके पंजीकरण करते हैं जो उन्हें एक स्थानीय डिजिटल प्रणाली से जोड़ता है।",
      step2Title: "शिकायत दर्ज करें और समाचार देखें",
      step2Desc: "सटीक स्थान विवरण के साथ पेयजल, बिजली या कचरे की समस्या दर्ज करें, योजना पात्रता जाँचें और गाँव की घोषणाएं देखें।",
      step3Title: "प्रशासनिक आवंटन व कार्य वितरण",
      step3Desc: "सरपंच और पंचायत अधिकारी शिकायतों का सत्यापन करते हैं, बजट आवंटित करते हैं, कार्यकर्ताओं को कार्य सौंपते हैं और चुनाव निर्धारित करते हैं।",
      step4Title: "सुधार कार्य और मतदान",
      step4Desc: "पंचायत कर्मी कार्य पूरा कर डिजिटल साक्ष्य अपलोड करते हैं। नागरिक प्रगति देख सकते हैं और वार्षिक चुनाव में मतदान करते हैं।",
      
      communityTitle: "सामुदायिक सहभागिता",
      communityDesc: "नागरिकों, स्वयंसेवकों और ग्रामीण नेताओं के बीच पारदर्शी संबंध स्थापित करना",
      comm1Title: "वार्षिक अधिकारी प्रदर्शन रैंकिंग",
      comm1Desc: "एक गाँव में एक से अधिक प्रशासक हो सकते हैं। नागरिक साल में एक बार मतदान कर उनकी कार्य गति और प्रतिक्रिया के आधार पर सर्वश्रेष्ठ नेता चुनते हैं।",
      comm2Title: "समय सीमा अनुपालन और कार्य ट्रैकिंग",
      comm2Desc: "हमारा सिस्टम औसत समाधान समय और विभाग की कार्य गति का सत्यापित रिकॉर्ड रखता है। नागरिक शिकायत की लाइव स्थिति देख सकते हैं।",
      comm1Badge: "लोकतांत्रिक जवाबदेही",
      comm2Badge: "पारदर्शी समाधान",
      comm1Footer: "ग्रामीण नागरिकों को स्थानीय शासन के प्रदर्शन में सीधी आवाज उठाने का अधिकार देता है।",
      comm2Footer: "सत्यापित साक्ष्य, लॉग और जवाबदेही डैशबोर्ड के माध्यम से विश्वास बढ़ाता है।",

      // SignUp page
      adminVerifRequired: "प्रशासनिक सत्यापन के लिए आवश्यक।",
      villageName: "ग्राम का नाम",
      male: "पुरुष",
      female: "महिला",
      other: "अन्य",
      registering: "पंजीकरण हो रहा है...",
      villageIdCitizenNote: "आपको वही ग्राम कोड दर्ज करना होगा जो आपके पंचायत अधिकारी ने पंजीकरण के दौरान उपयोग किया था।",

      // Register Complaint page
      registerNewComplaint: "नई शिकायत दर्ज करें",
      complaintHelperText: "हमारे स्वयंसेवकों को समस्या हल करने में मदद के लिए विस्तृत जानकारी दें।",
      complaintDetailsSection: "1. शिकायत विवरण",
      issueCategory: "समस्या की श्रेणी",
      waterLeakage: "पानी का रिसाव",
      roadDamage: "सड़क क्षति",
      garbageDump: "कचरा निपटान",
      electricityIssue: "बिजली की समस्या",
      drainageIssue: "जल निकासी की समस्या",
      priority: "प्राथमिकता",
      high: "उच्च",
      medium: "मध्यम",
      low: "निम्न",
      detailedDescription: "विस्तृत विवरण",
      visualEvidence: "2. दृश्य साक्ष्य और दस्तावेज़",
      uploadPrompt: "फोटो, वीडियो या दस्तावेज़ अपलोड करने के लिए क्लिक करें",
      uploadFormats: "चित्र (JPG, PNG), वीडियो (MP4), दस्तावेज़ (PDF, DOC)",
      uploadLimit: "अधिकतम 5 फ़ाइलें (प्रत्येक 10MB)",
      browseFiles: "फ़ाइलें देखें",
      locationSection: "3. स्थान की जानकारी",
      currentGPS: "वर्तमान GPS",
      manualEntry: "मैन्युअल प्रविष्टि",
      autoDetect: "मेरा स्थान स्वतः पहचानें",
      finalAddress: "अंतिम सत्यापित पता",
      detectedLocation: "पहचाना गया स्थान",
      registeringComplaint: "दर्ज हो रहा है...",
      ipLogNote: "सत्यापन के लिए आपका IP पता और स्थान दर्ज किया जाएगा।",

      // Citizen Profile page
      citizenProfile: "नागरिक प्रोफ़ाइल",
      editProfile: "प्रोफ़ाइल संपादित करें",
      handlingAdmin: "प्रबंधन करने वाले अधिकारी",
      noAdminFound: "कोई अधिकारी नहीं मिला",
      ensureVillageId: "सुनिश्चित करें कि आपका ग्राम कोड सही है।",
      basicDetails: "मूल विवरण",
      fullName: "पूरा नाम",
      save: "सहेजें",
      myAppliedSchemes: "मेरी आवेदित योजनाएं",
      trackApproval: "अपने जमा किए गए योजना आवेदनों की स्वीकृति और पात्रता ट्रैक करें।",
      noSchemesText: "सरकारी कल्याण कार्यक्रमों के लिए अपनी पात्रता जाँचने और ऑनलाइन पंजीकरण के लिए योजनाएं अनुभाग पर जाएं।",
      viewDocument: "दस्तावेज़ देखें",
      benefitStart: "लाभ शुरू:",
      benefitExpiry: "लाभ समाप्ति:",

      // Admin - Complaints Management
      workersActive: "कर्मचारी सक्रिय",
      complaintsDesc: "नागरिक रिपोर्टों की विस्तृत समीक्षा और समाधान।",
      allSubmissions: "सभी प्रस्तुतियाँ",
      searchComplaints: "आईडी या विवरण से खोजें...",
      allStatuses: "सभी स्थितियाँ",
      awaitingReview: "समीक्षा प्रतीक्षा में",
      complaintDetailsModal: "शिकायत विवरण",
      statusLabel: "स्थिति",
      assignedForce: "आवंटित कर्मचारी",
      actionsLabel: "कार्रवाई",
      viewLabel: "देखें",
      citizenDetails: "नागरिक विवरण",
      locationLabel: "स्थान",
      updateStatus: "स्थिति अपडेट करें",
      assignWorker: "कर्मचारी नियुक्त करें",
      noneOption: "कोई नहीं",
      noComplaintsFound: "वर्तमान खोज और फिल्टर से कोई शिकायत नहीं मिली।",
      loadingComplaints: "शिकायतें लोड हो रही हैं...",

      // Admin - Field Workers
      fieldWorkersDesc: "सक्रिय ग्रामसुविधा कार्यबल का प्रबंधन और ट्रैकिंग।",
      forceOverview: "कार्यबल अवलोकन",
      searchWorkers: "कर्मचारी खोजें...",
      workerIdentity: "कर्मचारी पहचान",
      areaVillage: "क्षेत्र / ग्राम",
      contactLabel: "संपर्क",
      demographics: "जनसांख्यिकी",
      activeWorker: "सक्रिय",
      onLeave: "छुट्टी पर",
      resigned: "इस्तीफा दिया",
      addNewWorker: "नया कर्मचारी जोड़ें",
      addWorkerDesc: "ग्रामसुविधा कार्यबल के लिए नए क्षेत्र कर्मचारी को पंजीकृत करें।",
      phoneNumber: "फ़ोन नंबर",
      workerVillageNote: "कर्मचारी स्वचालित रूप से आपके गाँव को आवंटित किया जाएगा।",
      clear: "साफ करें",
      registerWorker: "कर्मचारी पंजीकृत करें",
      noWorkersFound: "खोज से मेल खाने वाला कोई कर्मचारी नहीं मिला।",
      loadingWorkers: "कर्मचारी लोड हो रहे हैं...",
      workerSuccess: "कर्मचारी सफलतापूर्वक पंजीकृत!",

      // Admin - Scheme Applicants
      schemeApplicants: "योजना आवेदक",
      totalSubmissionsLabel: "कुल प्रस्तुतियाँ",
      schemeApplicantsDesc: "नागरिक कल्याण योजना आवेदनों की समीक्षा, अनुमोदन और प्रबंधन।",
      searchApplicants: "नाम, योजना, आईडी से खोजें...",
      pendingStatus: "लंबित",
      approvedStatus: "स्वीकृत",
      rejectedStatus: "अस्वीकृत",
      tooLateStatus: "बहुत देर",
      applicantRelAge: "आवेदक (संबंध, आयु)",
      idNumberCol: "पहचान संख्या",
      idProofCol: "पहचान प्रमाण",
      reviewLabel: "समीक्षा करें",
      reviewApplication: "आवेदन समीक्षा",
      editStatusParams: "स्थिति और वैधता पैरामीटर संपादित करें।",
      schemeLabel: "योजना",
      relationLabel: "संबंध",
      updateAppStatus: "आवेदन स्थिति अपडेट करें",
      benefitStartDate: "लाभ प्रारंभ तिथि",
      benefitExpiryDate: "लाभ समाप्ति तिथि",
      uploadedDocument: "अपलोड किया गया दस्तावेज़:",
      viewIdProof: "पहचान प्रमाण देखें ↗",
      noAppFound: "खोज मानदंड से मेल खाने वाला कोई आवेदन नहीं मिला।",
      loadingApps: "योजना आवेदन लोड हो रहे हैं...",

      // Citizen - Schemes page
      ageYears: "आयु (वर्ष)",
      annualIncome: "वार्षिक आय (₹)",
      socialCategory: "सामाजिक श्रेणी",
      selectCategory: "श्रेणी चुनें",
      primaryOccupation: "मुख्य व्यवसाय",
      selectOccupation: "व्यवसाय चुनें",
      recommendedSchemes: "अनुशंसित योजनाएं",
      highlyEligible: "अत्यधिक पात्र",
      youAreEligible: "आप पात्र हैं",
      applicationForm: "आवेदन फ़ॉर्म",
      applyingFor: "आवेदन किसके लिए",
      applicantNameLabel: "आवेदक का नाम",
      preFilled: "पात्रता मानदंड से पूर्व-भरा",
      idNumberLabel: "पहचान संख्या (आधार / पैन)",
      uploadIdProof: "पहचान प्रमाण अपलोड करें (स्कैन/फोटो)",
      submitting: "जमा हो रहा है...",
      submitApplication: "आवेदन जमा करें",
      applicationSubmitted: "आवेदन जमा हो गया!",
      schemeSubmittedDesc: "आपका आवेदन सफलतापूर्वक जमा हो गया है और समीक्षाधीन है।",
      alreadyRegisteredNotice: "सूचना: आप इस योजना के लिए पहले से पंजीकृत हैं संबंध के तहत",
      nodesOperational: "नोड्स सक्रिय",
      days7: "7 दिन",
      days30: "30 दिन",
      notifications: "सूचनाएं",
      noNotifications: "कोई नई सूचना नहीं",
      totalRequests: "कुल अनुरोध",
      pendingAction: "लंबित कार्रवाई",
      successfulResolutions: "सफल समाधान",
      activeVolunteers: "सक्रिय स्वयंसेवक",
      dailyVolumeDesc: "दैनिक जन भागीदारी की प्रवृत्ति।",
      liveStatusDesc: "सक्रिय परिचालन चरण।",
      complaintPriorities: "शिकायत प्राथमिकताएं",
      deptVelocityDesc: "श्रेणीवार प्रदर्शन संकेतक।",
      perfMatrixDesc: "मुख्य परिचालन प्रदर्शन संकेतक।",
      avgResolutionTime: "औसत समाधान समय",
      slaCompliance: "SLA अनुपालन (72 घंटे)",
      avgAssignments: "प्रति कार्यकर्ता औसत आवंटन",
      openTickets: "सक्रिय शिकायतें",
      citizensUnderAdminDesc: "आपके गाँव/वार्ड में पंजीकृत सभी नागरिकों की सूची।",
      totalCaps: "कुल",
      loadingCitizens: "नागरिक लोड हो रहे हैं...",
      noCitizensFound: "कोई नागरिक नहीं मिले",
      citizensRegisteringNote: "आपके ग्राम कोड के साथ पंजीकरण करने वाले नागरिक यहाँ दिखाई देंगे।",
      yrs: "वर्ष",
      notSpecified: "निर्दिष्ट नहीं",
      editAnnouncementDesc: "इस घोषणा के विवरण अपडेट करें",
      publishAnnouncementDesc: "चुनाव कार्यक्रम, जलापूर्ति समस्या, बिजली कटौती आदि घोषणाएं प्रकाशित करें।",
      updateAnnouncement: "घोषणा अपडेट करें",
      publishedUpdatesDesc: "नागरिकों को दिखाई देने वाली घोषणाओं की सूची।",
      noAnnouncements: "अभी तक कोई घोषणा प्रकाशित नहीं की गई है।",
      eventDateLabel: "घटना की तिथि",
      editLabel: "संपादित करें",
      deleteLabel: "हटाएं",
      scheduleYearlyElectionDesc: "गाँव के अधिकारियों के लिए मतदान की अवधि निर्धारित करें।",
      activeConfiguration: "सक्रिय सेटिंग्स:",
      yearLabel: "वर्ष",
      startLabel: "शुरू",
      endLabel: "समाप्त",
      electionsCurrentlyActive: "मतदान अभी सक्रिय है",
      electionsCurrentlyInactive: "मतदान अभी निष्क्रिय है",
      liveElectionStandingsDesc: "नागरिकों के वोटों पर आधारित प्रदर्शन लीडरबोर्ड।",
      systemOperationalLogs: "सिस्टम परिचालन लॉग",
      systemLogsDesc: "रीयल-टाइम स्थिति अपडेट और प्रशासनिक गतिविधि लॉग।",
      closeLogs: "लॉग बंद करें",
      updateSuccess: "घोषणा सफलतापूर्वक अपडेट की गई!",
      publishSuccess: "घोषणा सफलतापूर्वक प्रकाशित की गई!",
      deleteConfirm: "क्या आप वाकई इस घोषणा को हटाना चाहते हैं?",
      deleteSuccess: "घोषणा हटाने में विफल",
      networkError: "नेटवर्क त्रुटि",
      scheduling: "निर्धारित किया जा रहा है...",
      electionSaved: "चुनाव सफलतापूर्वक निर्धारित किया गया!",
      electionSaveFailed: "चुनाव निर्धारित करने में विफल"
    }
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return (
      (translations[language] && translations[language][key]) ||
      (translations.extra && translations.extra[language] && translations.extra[language][key]) ||
      key
    );
  };

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'hi' : 'en'));
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
